project1/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

project1/force-app/main/default/objects/Address__c/fields/Postal_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Zip_Code__c</fullName>
    <label>Postal/Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/Contact_Address__c.object-meta.xml
<CustomObject>
    <label>Contact-Address</label>
    <nameField>
        <label>Contact-Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact-Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contact-Address</relationshipLabel>
    <relationshipName>Contact_Address</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact-Address</relationshipLabel>
    <relationshipName>Contact_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>Mail-{000000}</displayFormat>
        <label>Mail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

project1/force-app/main/default/objects/Mail__c/fields/Contact_Address__c.field-meta.xml
<CustomField>
    <fullName>Contact_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Address</label>
    <referenceTo>Contact_Address__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Processed</fullName>
                <default>true</default>
                <label>Not Processed</label>
            </value>
            <value>
                <fullName>Information Received</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MailListWrapperControllerTest.cls
@isTest
public class MailListWrapperControllerTest {
    
    @testSetup
    public static void TestSetupMethod() {
        // Create test contact
        Contact tempContact = new Contact();
        tempContact.FirstName = 'Jackson';
        tempContact.LastName = 'Smith';
        insert tempContact;
        
        // Create test address
        Address__c tempAddr = new Address__c();
        tempAddr.Name = 'Smith Address';
        tempAddr.Address_Line_1__c = '123 Test St.';
        tempAddr.City__c = 'Los Angeles';
        tempAddr.State__c = 'CA';
        insert tempAddr;
        
        // Create test contact_address and relate to created address and contact
        tempContact = [SELECT FirstName, LastName, Id FROM Contact WHERE (FirstName='Jackson' AND LastName='Smith') LIMIT 1];
        tempAddr = [SELECT Name, Id, Address_Line_1__c, City__c FROM Address__c WHERE (Address_Line_1__c='123 Test St.' AND City__c='Los Angeles') LIMIT 1];
        Contact_Address__c tempConAddr = new Contact_Address__c();
        tempConAddr.Contact__c = tempContact.Id;
        tempConAddr.Address__c = tempAddr.Id;
        insert tempConAddr;
        
        // Store created contact_address
        List<Contact_Address__c> tempConAddrList = [SELECT Id, Contact__r.Id, Address__r.Id FROM Contact_Address__c];
        for(Contact_Address__c ca: tempConAddrList) {
            if(ca.Contact__r.Id==tempContact.Id && ca.Address__r.Id==tempAddr.Id) {
                tempConAddr = ca;
            }
        }

        // Create test mail and relate to created contact_address
        List<Mail__c> newMail = new List<Mail__c>();
        Mail__c tempMail1 = new Mail__c();
        tempMail1.Contact_Address__c = tempConAddr.Id;
        tempMail1.Delivery_Status__c = 'Lost';
        
        Mail__c tempMail2 = new Mail__c();
        tempMail2.Contact_Address__c = tempConAddr.Id;
        tempMail2.Delivery_Status__c = 'Delivered';
        
        Mail__c tempMail3 = new Mail__c();
        tempMail3.Contact_Address__c = tempConAddr.Id;
        tempMail3.Delivery_Status__c = 'In Transit';
        
        newMail.add(tempMail1);
        newMail.add(tempMail2);
        newMail.add(tempMail3);
        insert newMail;        
    }

    @isTest
    public static void TestMailListWrapperControllerConstructor() {
        MailListWrapperController.Wrapper testWrapper = new MailListWrapperController.Wrapper();
        MailListWrapperController testController = new MailListWrapperController();
       
        for(MailListWrapperController.Wrapper w: testController.mailList) {
            if(w.addr.Address_Line_1__c=='123 Test St.') {
                testWrapper = w;
            }
        }
        
        //System.assertEquals(testWrapper.addr.Address_Line_1__c, '123 Test St.');
        System.assertEquals(testWrapper.addr.Address_Line_2__c, null);
        System.assertEquals(testWrapper.addr.City__c, 'Los Angeles');
        System.assertEquals(testWrapper.addr.Postal_Zip_Code__c, null);
        System.assertEquals(testWrapper.addr.State__c, 'CA');
    }
    
    @isTest
    public static void TestFilter() {
        MailListWrapperController testController = new MailListWrapperController();
        Mail__c testValidMail = new Mail__c();
        Mail__c testInvalidMail = new Mail__c();
        
        testController.sample.Delivery_Status__c = 'Lost';
        testController.mailList.get(0).mail.Delivery_Status__c = 'Lost';
        testController.mailList.get(1).mail.Delivery_Status__c = 'Shipped';
        testController.mailList.get(2).mail.Delivery_Status__c = 'Lost';
        testValidMail = testController.mailList.get(0).mail;
        testInvalidMail = testController.mailList.get(1).mail;
        
        testController.Filter();
        System.assertEquals(testValidMail, testController.mailList.get(0).mail);
        System.assertNotEquals(testInvalidMail, testController.mailList.get(1).mail);
    }
    
    @isTest
    public static void TestShipping() {
        MailListWrapperController testController = new MailListWrapperController();
        Mail__c testValidMail = new Mail__c();
        Mail__c testInvalidMail = new Mail__c();
        
        testController.mailList.get(0).mail.Delivery_Status__c = 'In Transit';
        testController.mailList.get(1).mail.Delivery_Status__c = 'Delivered';
        testController.mailList.get(2).mail.Delivery_Status__c = 'Shipped';
        testValidMail = testController.mailList.get(0).mail;
        testInvalidMail = testController.mailList.get(1).mail;
        
        testController.Shipping();
        System.assertEquals(testValidMail, testController.mailList.get(0).mail);
        System.assertNotEquals(testInvalidMail, testController.mailList.get(1).mail);
    }
    
    @isTest
    public static void TestPast() {
        MailListWrapperController testController = new MailListWrapperController();
        Mail__c testValidMail = new Mail__c();
        Mail__c testInvalidMail = new Mail__c();
        
        testController.mailList.get(0).mail.Delivery_Status__c = 'Delivered';
        testController.mailList.get(1).mail.Delivery_Status__c = 'Shipped';
        testController.mailList.get(2).mail.Delivery_Status__c = 'Lost';
        testValidMail = testController.mailList.get(0).mail;
        testInvalidMail = testController.mailList.get(1).mail;
        
        testController.Past();
        System.assertEquals(testValidMail, testController.mailList.get(0).mail);
        System.assertNotEquals(testInvalidMail, testController.mailList.get(1).mail);
    }
    
    @isTest
    public static void TestRefreshView() {
        MailListWrapperController testController = new MailListWrapperController();                
        testController.mailList.remove(0);
        
        testController.RefreshView();
        System.assertEquals(testController.masterList, testController.mailList);
    }
        
}