project1/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

project1/force-app/main/default/objects/Address__c/fields/Postal_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Zip_Code__c</fullName>
    <label>Postal/Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/Contact_Address__c.object-meta.xml
<CustomObject>
    <label>Contact-Address</label>
    <nameField>
        <label>Contact-Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact-Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contact-Address</relationshipLabel>
    <relationshipName>Contact_Address</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact-Address</relationshipLabel>
    <relationshipName>Contact_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UserAccountController.cls
public class UserAccountController {

    public User currentUser{get;set;}
    public Account account{get;set;}
    public Contact contact{get;set;}
    public List<Address__c> addresses{get;set;}
    public Address__c address{get;set;}
    
    public Boolean disabled{get;set;}
    public Boolean show{get;set;}
    public Boolean hide{get;set;}
    
    public UserAccountController(){
       currentUser = [Select Username, Email, Firstname, Lastname, Name, ContactId From User Where Id = :UserInfo.getUserId()];
       contact = [Select Id, AccountId, Name, Phone, Email From Contact Where Id = :currentUser.ContactId];
       address = new Address__c();       
       List<Contact_Address__c> acList =  [Select Address__c From Contact_Address__c Where Contact__c = :contact.Id];
        
        List<ID> aListIds = new List<ID>();
        if(acList.size() > 0){
            for( Contact_Address__c ca: acList){
          		  aListIds.add(ca.Address__c);
        	}
        }
       
        addresses = (aListIds.size() > 0)?
            [Select Id, Name, Address_Line_1__c, Address_Line_2__c, City__c, Country__c, State__c, Postal_Zip_Code__c From Address__c Where Id in :aListIds]:
        	new List<Address__c>();
    	
        disabled = false;
        show = true;
        hide = false;
    }
   
    
    public void edit(){
         hide = !hide;
         show = !show;
    }

    public void save(){
        update currentUser;
       //if(this.addresses.size() > 0)
        update addresses;    
            
       hide = !hide;
        show = !show;
    }
    
    public void newAdd(){
        disabled = !disabled;
    }
    
    public void cancel(){
       hide = !hide;
        show = !show;
    }

  public void save2(){
        insert address;
        Contact_Address__c ca = new Contact_Address__c();
        ca.Name = contact.Name + '-' + address.Name;
        ca.Contact__c = contact.Id;
        ca.Address__c = address.Id;
        insert ca;
        disabled = !disabled;
    }
}