project1/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

project1/force-app/main/default/objects/Address__c/fields/Postal_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Zip_Code__c</fullName>
    <label>Postal/Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/Contact_Address__c.object-meta.xml
<CustomObject>
    <label>Contact-Address</label>
    <nameField>
        <label>Contact-Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact-Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contact-Address</relationshipLabel>
    <relationshipName>Contact_Address</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>Mail-{000000}</displayFormat>
        <label>Mail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

project1/force-app/main/default/objects/Mail__c/fields/Contact_Address__c.field-meta.xml
<CustomField>
    <fullName>Contact_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Address</label>
    <referenceTo>Contact_Address__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Processed</fullName>
                <default>true</default>
                <label>Not Processed</label>
            </value>
            <value>
                <fullName>Information Received</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

project1/force-app/main/default/objects/Mail__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <description>Height of package in inches</description>
    <inlineHelpText>Height of package in inches</inlineHelpText>
    <label>Height</label>
    <precision>7</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

project1/force-app/main/default/objects/Mail__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>Weight of package in pounds.</description>
    <inlineHelpText>Weight of package in pounds.</inlineHelpText>
    <label>Weight</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

project1/force-app/main/default/objects/Mail__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <description>Width of package in inches.</description>
    <inlineHelpText>Width of package in inches.</inlineHelpText>
    <label>Width</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TrackingCodeController.cls
public class TrackingCodeController {
    public Mail__c trackMail {get; set;}
    public String mailCode {get; set;}
    public String searchMessage {get; set;}
    public Boolean showFields {get; set;}
    public Boolean showMessage {get; set;}
    
    public TrackingCodeController() {
        //trackMail = new Mail__c();
        showFields = false;
        showMessage = false;
    }
    
    public void SearchCode() {
		// Reset values
		showFields = false;
        showMessage = false;
        
        if(mailCode.length() != 15) {
            searchMessage = 'Error: Enter valid tracking code';
            showMessage = true;
        }
        
        for(Mail__c m:[SELECT Name, Id, Delivery_Status__c, Height__c, Weight__c, Width__c, Contact_Address__c, Contact_Address__r.Address__c, 
                   Contact_Address__r.Address__r.Address_Line_1__c, Contact_Address__r.Address__r.Address_Line_2__c, 
                   Contact_Address__r.Address__r.City__c, Contact_Address__r.Address__r.Postal_Zip_Code__c, 
                   Contact_Address__r.Address__r.State__c FROM Mail__c]) {
            // Only take 15 digit Id
            String strId = Id.valueOf(m.Id); 
            strId = strId.substring(0,15);

            if(strId == mailCode) {
                trackMail = m;
                showFields = true;
                showMessage = false;
            }
        }
        
        if(showFields == false && showMessage == false) {
            searchMessage = 'No package not found';
            showMessage = true;
        }
    }
}