project1/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

project1/force-app/main/default/objects/Address__c/fields/Postal_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Zip_Code__c</fullName>
    <label>Postal/Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/Contact_Address__c.object-meta.xml
<CustomObject>
    <label>Contact-Address</label>
    <nameField>
        <label>Contact-Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact-Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contact-Address</relationshipLabel>
    <relationshipName>Contact_Address</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>Mail-{000000}</displayFormat>
        <label>Mail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

project1/force-app/main/default/objects/Mail__c/fields/Contact_Address__c.field-meta.xml
<CustomField>
    <fullName>Contact_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Address</label>
    <referenceTo>Contact_Address__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Processed</fullName>
                <default>true</default>
                <label>Not Processed</label>
            </value>
            <value>
                <fullName>Information Received</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MailListWrapperController.cls
public class MailListWrapperController {
	public List<Wrapper> mailList {get; set;}
    public Mail__c sample {get; set;}
    
    public MailListWrapperController() {
        mailList = new List<Wrapper>();
        for(Mail__c m: [SELECT Id, Delivery_Status__c, Contact_Address__c, Contact_Address__r.Address__c, 
                        Contact_Address__r.Address__r.Address_Line_1__c, Contact_Address__r.Address__r.Address_Line_2__c, 
                        Contact_Address__r.Address__r.City__c, Contact_Address__r.Address__r.Postal_Zip_Code__c, 
                        Contact_Address__r.Address__r.State__c FROM Mail__c]) {
            Wrapper temp = new Wrapper();
            temp.mail = m;
            temp.conAddr = new Contact_Address__c();
            temp.conAddr.Id = m.Contact_Address__c;           
            temp.currView = true;
            temp.addr = new Address__c();
            temp.addr.Id = m.Contact_Address__r.Address__c;
            temp.addr.Address_Line_1__c = m.Contact_Address__r.Address__r.Address_Line_1__c;
            temp.addr.Address_Line_2__c = m.Contact_Address__r.Address__r.Address_Line_2__c;
            temp.addr.City__c = m.Contact_Address__r.Address__r.City__c;
			temp.addr.Postal_Zip_Code__c = m.Contact_Address__r.Address__r.Postal_Zip_Code__c;
            temp.addr.State__c = m.Contact_Address__r.Address__r.State__c;                
                            
            
            mailList.add(temp);
        }       

		sample = new Mail__c();        
    }
    
    public class Wrapper {
        public Mail__c mail {get; set;}
        public Contact_Address__c conAddr {get; set;}
        public Address__c addr {get; set;}
        public boolean currView {get; set;}
    }
    
    public void filter() {
        refreshView();
        
        for(Wrapper w:mailList) {
            if(w.mail.Delivery_Status__c != sample.Delivery_Status__c) {
                w.currView = false;
            }
        }
    }
    
    public void refreshView() {
        for(Wrapper w:mailList) {
            w.currView = true;
        }
    }

}